services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      # 🧩 Add your secrets here (Hostinger will inject these)
      - DATABASE_URL='postgresql://neondb_owner:npg_HFWXvYV9ZmO0@ep-quiet-bonus-af100h96-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require'
      - APP_URL=https://daifend.ai
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      # Make sure your local Caddyfile exists at project root
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
