services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: "5000"
      # 🔐 replace with your real connection string
      DATABASE_URL: "postgresql://neondb_owner:npg_HFWXvYV9ZmO0@ep-quiet-bonus-af100h96-pooler.c-2.us-west-2.aws.neon.tech/neondb?sslmode=require&channel_binding=require"
      # EMAIL_HOST: "smtp-relay.brevo.com"
      # EMAIL_USER: "<brevo-user>"
      # EMAIL_PASS: "<brevo-pass>"
    expose:
      - "5000"
    restart: unless-stopped

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy   # Caddyfile baked into the image
    container_name: caddy
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    environment:
      # ✅ Let’s Encrypt production (you may omit; prod is default)
      CADDY_ACME_CA: "https://acme-v02.api.letsencrypt.org/directory"
      CADDY_ADMIN_EMAIL: "rahul@daifend.ai"
    volumes:
      - caddy_data:/data    # persist certs (prevents rate-limits on redeploys)
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
