services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    expose:
      - "5000"
    restart: unless-stopped

  caddy:
    build:
      context: .
      dockerfile: Dockerfile.caddy
    container_name: caddy
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
