services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ./.env
    expose:
      - "5000"             # internal only; Caddy will reverse-proxy to this
    restart: unless-stopped

  caddy:
    image: caddy:2
    container_name: caddy
    depends_on:
      - app
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy:ro   # commit this folder with Caddyfile inside
      - caddy_data:/data
      - caddy_config:/config
    restart: unless-stopped

volumes:
  caddy_data:
  caddy_config:
